version: '3.8'

services:
  web:
    build: ./src
    container_name: container-app-async
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/
    ports:
      - 8000:8000
    tty: true
    environment:
      - DATABASE_URL=postgresql://learning:learning@db/learning
    depends_on:
      - db

  db:
    image: postgres:15.1-alpine
    volumes:
      # - ./init-scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5433:5433"
    expose:
      - 5433
    environment:
      - POSTGRES_USER=learning
      - POSTGRES_PASSWORD=learning
      - POSTGRES_DB=learning
      - POSTGRES_HOST=localhost
    tty: true
    
volumes:
  postgres_data: