version: '3.8'

services:
  web:
    build: ./src
    container_name: container-app-async
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 8000
    volumes:
      - ./src:/usr/src/
    ports:
      - 8002:8000